version: '3.8'

services:
  auth-db:
    image: postgres
    container_name: auth-db
    restart: always
    environment: 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports: 
     - "5432:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data
    networks:
     - auth-network  

  adminer: 
    image: adminer
    restart: always
    ports: 
     - "8080:8080"
    networks:
     - auth-network

volumes:
  postgres_data:

networks:
  auth-network:
    driver: bridge